
// Objective-C API for talking to the following Go packages
//
//	github.com/elliottech/lighter-go/mobile
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Lighter_FRAMEWORK_H__
#define __Lighter_FRAMEWORK_H__

#include "Mobile.objc.h"
#include "Universe.objc.h"

#endif
