// Objective-C API for talking to github.com/elliottech/lighter-go/mobile Go package.
//   gobind -lang=objc github.com/elliottech/lighter-go/mobile
//
// File is generated by gobind. Do not edit.

#ifndef __Mobile_H__
#define __Mobile_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class MobileAPIKeyResult;
@class MobileTxResult;

/**
 * APIKeyResult holds the result of API key generation
 */
@interface MobileAPIKeyResult : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull privateKey;
@property (nonatomic) NSString* _Nonnull publicKey;
@property (nonatomic) NSString* _Nonnull error;
@end

/**
 * TxResult holds the result of a transaction signing operation
 */
@interface MobileTxResult : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull json;
@property (nonatomic) NSString* _Nonnull error;
@end

/**
 * CheckClient verifies that the client is properly configured and matches the API key on Lighter
 */
FOUNDATION_EXPORT NSString* _Nonnull MobileCheckClient(long apiKeyIndex, int64_t accountIndex);

/**
 * CreateAuthToken creates an authentication token
deadline: Unix timestamp, use 0 for default (7 hours from now)
 */
FOUNDATION_EXPORT MobileTxResult* _Nullable MobileCreateAuthToken(int64_t deadline);

/**
 * CreateClient creates a new transaction client
url: API endpoint URL
privateKey: hex-encoded private key
chainId: blockchain chain ID
apiKeyIndex: index of the API key (0-255)
accountIndex: account index (must be > 0)
 */
FOUNDATION_EXPORT NSString* _Nonnull MobileCreateClient(NSString* _Nullable url, NSString* _Nullable privateKey, long chainId, long apiKeyIndex, int64_t accountIndex);

/**
 * GenerateAPIKey generates a new API key pair from an optional seed
Pass empty string for seed to generate random key
 */
FOUNDATION_EXPORT MobileAPIKeyResult* _Nullable MobileGenerateAPIKey(NSString* _Nullable seed);

/**
 * SignBurnShares signs a burn shares transaction
 */
FOUNDATION_EXPORT MobileTxResult* _Nullable MobileSignBurnShares(int64_t publicPoolIndex, int64_t shareAmount, int64_t nonce);

/**
 * SignCancelAllOrders signs a cancel all orders transaction
 */
FOUNDATION_EXPORT MobileTxResult* _Nullable MobileSignCancelAllOrders(long timeInForce, int64_t time, int64_t nonce);

/**
 * SignCancelOrder signs a cancel order transaction
 */
FOUNDATION_EXPORT MobileTxResult* _Nullable MobileSignCancelOrder(long marketIndex, int64_t orderIndex, int64_t nonce);

/**
 * SignChangePubKey signs a change public key transaction
pubKey: hex-encoded new public key (40 bytes)
nonce: transaction nonce, use -1 for automatic
 */
FOUNDATION_EXPORT MobileTxResult* _Nullable MobileSignChangePubKey(NSString* _Nullable pubKey, int64_t nonce);

/**
 * SignCreateGroupedOrders signs a create grouped orders transaction
ordersJSON should be a JSON array of order objects
groupingType: 0 = None, 1 = OCO (One-Cancels-Other), 2 = OTO (One-Triggers-Other), 3 = OTOCO
 */
FOUNDATION_EXPORT MobileTxResult* _Nullable MobileSignCreateGroupedOrders(long groupingType, NSString* _Nullable ordersJSON, int64_t nonce);

/**
 * SignCreateOrder signs a create order transaction
Pass -1 for orderExpiry to use default (28 days)
Pass -1 for nonce for automatic nonce
 */
FOUNDATION_EXPORT MobileTxResult* _Nullable MobileSignCreateOrder(long marketIndex, int64_t clientOrderIndex, int64_t baseAmount, long price, long isAsk, long orderType, long timeInForce, long reduceOnly, long triggerPrice, int64_t orderExpiry, int64_t nonce);

/**
 * SignCreatePublicPool signs a create public pool transaction
 */
FOUNDATION_EXPORT MobileTxResult* _Nullable MobileSignCreatePublicPool(int64_t operatorFee, int64_t initialTotalShares, int64_t minOperatorShareRate, int64_t nonce);

/**
 * SignCreateSubAccount signs a create sub account transaction
 */
FOUNDATION_EXPORT MobileTxResult* _Nullable MobileSignCreateSubAccount(int64_t nonce);

/**
 * SignMintShares signs a mint shares transaction
 */
FOUNDATION_EXPORT MobileTxResult* _Nullable MobileSignMintShares(int64_t publicPoolIndex, int64_t shareAmount, int64_t nonce);

/**
 * SignModifyOrder signs a modify order transaction
 */
FOUNDATION_EXPORT MobileTxResult* _Nullable MobileSignModifyOrder(long marketIndex, int64_t index, int64_t baseAmount, int64_t price, int64_t triggerPrice, int64_t nonce);

/**
 * SignTransfer signs a transfer transaction
memo must be exactly 32 bytes
 */
FOUNDATION_EXPORT MobileTxResult* _Nullable MobileSignTransfer(int64_t toAccountIndex, int64_t usdcAmount, int64_t fee, NSString* _Nullable memo, int64_t nonce);

/**
 * SignUpdateLeverage signs an update leverage transaction
 */
FOUNDATION_EXPORT MobileTxResult* _Nullable MobileSignUpdateLeverage(long marketIndex, long initialMarginFraction, long marginMode, int64_t nonce);

/**
 * SignUpdateMargin signs an update margin transaction
 */
FOUNDATION_EXPORT MobileTxResult* _Nullable MobileSignUpdateMargin(long marketIndex, int64_t usdcAmount, long direction, int64_t nonce);

/**
 * SignUpdatePublicPool signs an update public pool transaction
 */
FOUNDATION_EXPORT MobileTxResult* _Nullable MobileSignUpdatePublicPool(int64_t publicPoolIndex, long status, int64_t operatorFee, int64_t minOperatorShareRate, int64_t nonce);

/**
 * SignWithdraw signs a withdraw transaction
 */
FOUNDATION_EXPORT MobileTxResult* _Nullable MobileSignWithdraw(int64_t usdcAmount, int64_t nonce);

/**
 * SwitchAPIKey switches the active API key to the one at the specified index
 */
FOUNDATION_EXPORT NSString* _Nonnull MobileSwitchAPIKey(long apiKeyIndex);

#endif
